from pathlib import Path

ROOT_FOLDER = Path(__file__).parent.parent
SCRIPTS_FOLDER = ROOT_FOLDER / "scripts"
DOWNLOADS_FOLDER = SCRIPTS_FOLDER / "downloads"
SQL_FOLDER = SCRIPTS_FOLDER / "sql"
RATINGS_FILEPATH = DOWNLOADS_FOLDER / "title.ratings.tsv"
BASICS_FILEPATH = DOWNLOADS_FOLDER / "title.basics.tsv"
BASICS_FILTERED_FILEPATH = DOWNLOADS_FOLDER / "title.basics.filtered.tsv"
EPISODE_INDEX_FILEPATH = DOWNLOADS_FOLDER / "title.episode.tsv"

# The line count of the files as of 2023-02-18
RATINGS_EST_SIZE = 1280583
EPISODE_INDEX_EST_SIZE = 7291989
BASICS_EST_SIZE = 9624114
BASICS_FILTERED_EST_SIZE = 7531134
