version: '3'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: imdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      PGHOST: db
      PGDATABASE: imdb
      PGUSER: postgres
      PGPASSWORD: postgres

